# Generated by Django 2.0 on 2018-01-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180101_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='artwork_url',
            field=models.CharField(blank=True, help_text='Enter url of movie artwork', max_length=400, null=True),
        ),
    ]
