# Generated by Django 2.0 on 2018-01-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180106_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='artwork',
        ),
    ]
