# Generated by Django 2.0 on 2018-01-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_movie_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Enter moovies rating', max_digits=3, null=True),
        ),
    ]
